ClassCastException in "Apply all fixes"
The code contained an unchecked cast, and the declaration of the called
method had changed in the past, therefore making this incompatible.

java.lang.ClassCastException: class [Lorg.eclipse.ui.IMarkerResolution;
cannot be cast to class
[Lnet.sf.eclipsecs.ui.quickfixes.ICheckstyleMarkerResolution;
([Lorg.eclipse.ui.IMarkerResolution; is in unnamed module of loader
org.eclipse.osgi.internal.loader.EquinoxClassLoader @6be67f3a;
[Lnet.sf.eclipsecs.ui.quickfixes.ICheckstyleMarkerResolution; is in
unnamed module of loader
org.eclipse.osgi.internal.loader.EquinoxClassLoader @138bfa5)
	at net.sf.eclipsecs.ui.quickfixes.FixCheckstyleMarkersJob.runInUIThread(FixCheckstyleMarkersJob.java:68)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)